platform :ios, '6.0'
pod 'AFNetworking'
pod 'AFDownloadRequestOperation'
pod 'FMDB'
pod 'TestFlightSDK'
pod 'Godzippa'
pod 'QuickDialog', :git => 'git@github.com:xhacker/QuickDialog.git'
pod 'MBProgressHUD', '~> 0.6'