platform :ios, '6.0'
pod 'AFNetworking'
pod 'AFDownloadRequestOperation'
pod 'FMDB'
pod 'TestFlightSDK'
pod 'Godzippa'
pod 'QuickDialog', :git => 'https://github.com/escoz/QuickDialog.git', :commit => 'c89e8ccea8'